### ISSUE TITLE
All in one check and report switch 

### ISSUE THREAD

**Issue by mrrrmeow** [silverhack/monkey365#100]
**Is your feature request related to a problem? Please describe.**
Hi, I just can't find the ALL-in-one testing switch so that i could check everything what tenant has - in azure, sharepoint, exchange online, teams and the rest. Can you implement such or point me to the right direction? P.S. using the latest develop version 

**Describe the solution you'd like**
ALL-in-one testing switch so that i could check everything what tenant has

**Describe alternatives you've considered**
running several items one by one

**Additional context**

Many thanks!

**Comment by silverhack** [comment]
Hi @mrrrmeow, 

We're currently not considering to add this feature. Just to mention that the ALL option is only present on Azure checks, and there is no plans to include the ALL option within Microsoft 365 instance or even a check to start a all-cloud-scans. Please, see the docs if you need to scan [multiple subscriptions](https://silverhack.github.io/monkey365/configuration/azure-options/). 

Thanks for using Monkey365!
