### ISSUE TITLE
[Bug]: In import module monkey365.psm1

### ISSUE THREAD

**Issue by digitalarche** [silverhack/monkey365#102]
![image](https://github.com/silverhack/monkey365/assets/6546135/0d1ff599-545a-49b4-9dd8-dffe254178fc)

The command [System.IO.Directory]::EnumerateFiles make a error on the array internal_functions because there are a 
'core/watcher' and this path don't exist or don't exist yet :) as like see on my capture just remove it or make a comment.  

I leave it to you to decide which modification will be the best solution for you.  Have a great day.

**Comment by silverhack** [comment]
Hey @digitalarche,

It's the same as [https://github.com/silverhack/monkey365/issues/87](https://github.com/silverhack/monkey365/issues/87) was fixed some months ago in dev branch. Hopefully I'll have some time on this week to update the main branch with this and other improvements. 

Cheers

**Comment by Franck-CMA** [comment]
Sorry don't see it before effectively. Sorry again.

**Comment by silverhack** [comment]
No worries and thanks for using Monkey365 🤘😎🤘

**Comment by silverhack** [comment]
This is now updated in [main release](https://github.com/silverhack/monkey365/releases/tag/v0.91.3-beta). 

Cheers,
