### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by t3hbb** [silverhack/monkey365#12]
**What happened?**  
Had a finding reported for excessive number of global administrators *and* low number of global administrators

**How to reproduce it**  
Run the tool against a tenant with 4 Global Administrators

**Expected behavior**  
The two findings are mutually exclusive. This should not happen.

**Screenshots or Logs**  
Global Admins present : 
![image](https://user-images.githubusercontent.com/21687763/183673299-7b30667a-37c5-4e08-9fd3-e334f2f8c8e8.png)

Report Findings 

![image](https://user-images.githubusercontent.com/21687763/183673588-054cd73d-5a35-477c-aaa3-396e42d79339.png)

**From where are you running Monkey365?**  
Please, complete the following information:

 - OS: Windows
 - PowerShell Version [`$PsVersionTable`]: 5.1.19041.1682
 - Monkey365 Version: Latest download as of 09/08/2022
 - Others:

**Comment by silverhack** [comment]
Hi, what you are seeing is completely normal. Please note that findings marked as “green” are goods findings, and it means that no issue was found and configuration is OK. If you execute Monkey365 against a tenant with only one global administrator you will get the opposite. The “excessive number of global admins” will be marked as good (green) and the “low number of global admin” will be flagged as an issue. 
hope that helps

**Comment by t3hbb** [comment]
OK - I see that now thank you.

Tangentially related question (and partially the reason I thought this was an issue) - is there a reason this flags on 4 rather than 5 when the 365 Benchmark says between two and four should be configured? 

Many thanks

**Comment by silverhack** [comment]
Well you can modify the behavior of the rule to fit your expectations. I’ll update the rule to flag the exact number of CIS

**Comment by silverhack** [comment]
Hi, this is now changed in Develop. 

Cheers,
