### ISSUE TITLE
[ Bug but more improvement ;) ]: In your Monkey365.psm1

### ISSUE THREAD

**Issue by digitalarche** [silverhack/monkey365#15]
**From where are you running Monkey365?**  
Please, complete the following information:
 - Resource: [workstation]
 - OS: [Windows 11 [version 10.0.22000.856] ]
 - PowerShell Version Both 7.x and 5.1:
 Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name                           Value                                                                                                                                                                                  
----                           -----                                                                                                                                                                                  
PSVersion                      5.1.22000.832                                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                
BuildVersion                   10.0.22000.832                                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                                    
SerializationVersion           1.1.0.1

 - Monkey365 Version: Latest 
 
 - Others: 
 Release   NetFramework 
--------    ------- 
528449    4.8

=========================================================
The issue is inside the file PSM1 during the installation of the module. 
In the loop to go to load depending on whether it is a directory or not and if we are in the directories that have PSMs to declare. 

Indeed, when The file or directory will not be indexed by the operating system's content indexing service.
You receive this as result: "Directory, NotContentIndexed" and not just: "Directory" when you call the static GetAttributes() method. Moreover, your $metadata variable gets the return type of the method which is an Enum type and not a String type. 
You can see it here: https://referencesource.microsoft.com/#mscorlib/system/io/fileattributes.cs

```
$metadata = [System.IO.File]::GetAttributes(("{0}{1}" -f $PSScriptRoot, $module.value))
[[  if($metadata -eq "Directory")  ]]
```
In this case the equation does not work because the "-eq" returns false. 

```
$Modules = @{
    utils = "/core/utils/"
    azure_api = "/core/api/azure/"
    init = "/core/init/"
    runspaces = "/core/tasks/"
    auth = "/core/api/auth/"
    analysis = "/core/analysis/"
    office = "/core/office/"
    html = "/core/html/"
    o365_api = "/core/api/o365/"
    watcher = "/core/watcher/"
    output = "/core/output/"
    import = "/core/import/"
}
#Import modules
foreach($module in $Modules.GetEnumerator()){
    $metadata = ([System.IO.File]::GetAttributes(("{0}{1}" -f $PSScriptRoot, $module.value))).ToString()
    if($metadata.split(",")[0] -eq "Directory"){
        $all_files = Get-ChildItem -Recurse -Path ("{0}{1}" -f $PSScriptRoot, $module.value) -File -Include "*.ps1" -ErrorAction SilentlyContinue
        if($null -ne $all_files){
            foreach ($mod in $all_files){
                Write-Verbose ("Loading {0} module" -f $mod.FullName)
                . $mod.FullName
            }
        }
    }
    else{
        Write-Verbose ("Loading {0} module" -f $module.Name)
        $tmp_module = ("{0}{1}" -f $PSScriptRoot, $module.value)
        . $tmp_module.ToString()
    }
}
```

This results in not loading all *.ps1 files in the respective directories. Since it passes in the Else to load modules. 

By the way, if I can add another concern that is related to this one, it is that I don't think you need to do this Conditional Statements since you load your modules afterwards in the New-O365Object.ps1 file. 

So I was going to tell you to do a ".ToString()" behind your GetAttributes() and then do a "-like" or rather a "split()" on your $metadata variable. 

But then you don't put the Modules directory in your list anymore and everything else is really folders with ".ps1" files to load so I think just putting your loop with the Core of the first IF would be enough I think like this: 

```

$all_files = Get-ChildItem -Recurse -Path ("{0}{1}" -f $PSScriptRoot, $module.value) -File -Include "*.ps1" -ErrorAction SilentlyContinue
if($null -ne $all_files){
    foreach ($mod in $all_files){
        Write-Verbose ("Loading {0} module" -f $mod.FullName)
        . $mod.FullName
    }
}
```
I was able to test it on an indexed and non-indexed machine and it works in both Posh 7.x and 5.x. 

If you agree with my observation I can do the PR if you want if not I let you correct it. 

I remind you that you remove the indexing as I did when you have SSDs disks in the machine and as much in VMs with SSD. You would have had the problem one day or another. 

A few other bugs I'll reference later and separate them for you but really an amazing super job. 
Have a great day. Franck.

**Comment by silverhack** [comment]
Hi and thanks for submitting this. 

As a side note I think that this isn’t really true. Indexing builds a list of the files on your drive and using the search index on your computer/folder will be pretty much faster when you're searching for a particular type or even performing instant full-text search. With indexing disabled, the OS will have to crawl all your drive/folder and look into files, so it will take some time and resources. 

Having said that, the code was modified to use bitwise and (-band) in order to test whether the "Directory" bit is set. It should be fixed now in dev branch.

In the following image you can see how values are evaluated. 

<img width="1145" alt="DirectoryNotContentIndexed" src="https://user-images.githubusercontent.com/5271640/187259978-e43e407e-2f19-4a29-8932-6791804a634d.PNG">

Cheers,
