### ISSUE TITLE
[Bug In Method Invoke-HtmlReport]: 

### ISSUE THREAD

**Issue by digitalarche** [silverhack/monkey365#16]
From where are you running Monkey365?
Please, complete the following information:

Resource: [workstation]
OS: [Windows 11 [version 10.0.22000.856] ]
PowerShell Version Both 7.x and 5.1:
Name Value
PSVersion 7.2.6
PSEdition Core
GitCommitId 7.2.6
OS Microsoft Windows 10.0.22000
Platform Win32NT
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
WSManStackVersion 3.0

Name Value

PSVersion 5.1.22000.832
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.22000.832
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

Monkey365 Version: Latest

Others:
Release        NetFramework
528449         4.8

======================================  The error 

WARNING: [17:27:48:634] - [Invoke-HtmlReport] - Monkey365/core/html/htmlconf/charts does not exists - 
WARNING: [17:27:48:636] - [Invoke-HtmlReport] - Monkey365/core/html/htmlconf/dashboards does not exists - 

I think you are rewriting or refactoring because in the Core\htmlconf directory actually there is only the tables directory with subdirectories and declarative json files. 

I think you must be referring to the files that are now in the Modules\monkeyhtml directory and in the private subdirectory there are two directories respectively htmlcharts and htmldashboard. 

This is in your Config Monkey Json file because in the current version there are inserted:

```
"htmlSettings": {
        "tableformat": "core/html/htmlconf/tables",
        "chartformat": "core/html/htmlconf/charts",
        "dashboardformat": "core/html/htmlconf/dashboards"
    },

```
This is strange since since the initial commit these directories never existed. On the other hand, in Invoke-HtmlReport there is the code to test and load it as for the Dashboard part. 

```
$chartPath = $O365Object.internal_config.htmlSettings.chartformat
$isRoot = [System.IO.Path]::IsPathRooted($chartPath)
if(-NOT $isRoot){
       $chartPath = ("{0}/{1}" -f $O365Object.Localpath, $chartPath)
}
if (!(Test-Path -Path $chartPath)){
       Write-Warning ("{0} does not exist" -f $chartPath)
}
```
We fall directly into the warning.         

The same goes for the DashboardPath. 
`$dashboardPath = $O365Object.internal_config.htmlSettings.dashboardformat`

Finally it follows the same path as in Table in the code which works very well. 
Is it still useful ? Or are there any files missing? Or did you do something different? 
Thank you. Franck.

**Comment by silverhack** [comment]
Hi @digitalarche and thanks for submitting this. It's not a bug and code is not breaking any functionality. I'm currently testing the possibility of adding new components to HTML report, such as dynamic charts and dashboards. 

I will remove these lines of code in both main and dev branch.

Cheers,

**Comment by silverhack** [comment]
Hi @digitalarche. Changes were applied to DEV branch. Main branch will be updated soon.
