### ISSUE TITLE
[Bug]:  MDE / EDR blocks executing this script/function. This morning it was working fine. This evening it's blocked.

### ISSUE THREAD

**Issue by hardinxcore** [silverhack/monkey365#20]
![image](https://user-images.githubusercontent.com/34623288/187778722-b879f9bc-254c-4f2a-a028-0a81617f8ecd.png)

**Comment by silverhack** [comment]
Hey and thanks a for submitting this. I can’t reproduce it but as far as I can see you’re using an incorrect format in LogFile. You’re using %date% which is not allowed by the tool. Could you please try again? Also it would be great if you can also share the code which is causing the exception. Thanks

**Comment by hardinxcore** [comment]
After installing Monkey365 I execute(d) this lines:

#MS365
$param = @{
    Instance = 'Office365';
    Analysis = 'SharePointOnline';
    PromptBehavior = 'SelectAccount';
    IncludeAzureActiveDirectory = $true;
    #ExportTo = 'PRINT';
    #ExportTo = 'CLIXML,EXCEL,CSV,JSON,HTML';
    ExportTo = 'HTML';
}
$assets = Invoke-Monkey365 @param

#Azure
$param = @{
    Instance = 'Azure';
    Analysis = 'All';
    PromptBehavior = 'SelectAccount';
    #subscriptions = 'a8d18a12-3e3a-49a7-97af-917a0436eac4';
    all_subscriptions = $true;
    TenantID = 'f16370b9-be75-4bf8-b8de-3c3f7382cc33';
    #ExportTo = 'PRINT';
    #ExportTo = 'CLIXML,EXCEL,CSV,JSON,HTML';
    ExportTo = 'HTML';
}
$assets = Invoke-Monkey365 @param

**Comment by silverhack** [comment]
Hi. Could you please test it in other environments, such as a new PowerShell console? More info is needed, for example the EDR log. The tool is not reading any raw keystroke data, and is not hooking any API call from the system. Also the tool is heavily tested in multiple OS, with multiple configurations and AV solutions and for that reason I think that it could be a false positive. 

Thanks

**Comment by silverhack** [comment]
Hi @hardinxcore, is there any update on this? 

Thanks in advance

**Comment by hardinxcore** [comment]
I have to find time to run this within a vm without MDE running. I hope to do this on Monday. 

My Win11 laptop with MDE is still blocking this.

**Comment by silverhack** [comment]
Hi @hardinxcore thanks for quick response. It's really appreciated. 

I was able to reproduce the issue with EDR. In my specific lab, apart from Invoke-MonkeyLogger, there were some files detected as potentially malicious, as shown below:
<img width="994" alt="FalsePositive" src="https://user-images.githubusercontent.com/5271640/188285535-8a2226bd-280f-4525-9c0a-afba1c71a3e3.PNG">

<img width="978" alt="FalsePositive2" src="https://user-images.githubusercontent.com/5271640/188285560-9a446334-c6d3-4c7f-b987-1b14d1525e2c.PNG">

So I would recommend to mark these files as a False positive, as these functions are designed to perform internal tasks, such as converting GUIDs to names, logging utilities to forward logs to Teams or Slack, or HTML utilities to convert metadata to tables. 

I can confirm that it's a false positive in Microsoft Defender. Feel free to analyze the source code or to send files to MS for review. 

More information regarding False/True positives in Microsoft Defender is showing here:

[https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide](url)

Thanks,
