### ISSUE TITLE
[Bug]: Update documentation

### ISSUE THREAD

**Issue by michaelbaltes** [silverhack/monkey365#24]
Udpate your documentation because there is a little error on https://silverhack.github.io/monkey365/configuration/general-options/

under -Instance 
change the value from Office365 to Microsoft365.

![image](https://user-images.githubusercontent.com/34088306/194052707-ec3271b6-a3d1-4fbe-8dad-88279a701dc5.png)

**Comment by silverhack** [comment]
Hi @michaelbaltes and thanks for submitting this! This is now fixed in both dev and main branches. 

Cheers
