### ISSUE TITLE
[Bug]: Empty response

### ISSUE THREAD

**Issue by burak40** [silverhack/monkey365#31]
I use this script 

$assets = Invoke-Monkey365 -ExportTo PRINT -PromptBehavior SelectAccount -IncludeAzureActiveDirectory -Instance Microsoft365 -Analysis SharePointOnline

I get these results

WARNING: [12:30:47:141] - [Get-MonkeyADApplication] - The Applications Role Assignments query did not return any data in 00000-xxxx-xxx tenant - warning - - AzureGraphAppRBACEmptyResponse
WARNING: [12:31:08:500] - [Get-MonkeyADPasswordPolicy] - The Azure AD password template policy query did not return any data in 00000-xxxx-xxx tenant - warning - - AzurePortalTemplatePolicyEmptyResponse
WARNING: [12:31:10:193] - [Get-MonkeyADPortalDeviceSetting] - The Azure AD device settings query did not return any data in 00000-xxxx-xxx-tenant - warning - # - AzurePortalDevicesEmptyResponse
WARNING: [12:31:12:544] - [Get-MonkeyADDirectoryProperty] - The Azure AD B2B directory properties query did not return any data in 00000-xxxx-xxx- tenant - warning -  - AzurePortalEmptyResponse
WARNING: [12:31:13:903] - [Get-MonkeyADRoamingInfo] - The Azure AD Roaming properties query did not return any data in 00000-xxxx-xxx- tenant - warning -  - AzurePortalRoamingEmptyResponse
WARNING: [12:31:14:627] - [Get-MonkeySPSWebsForUser] - Unable to get site properties for  - warning -  - SPSUnableToGetSites
WARNING: [12:31:15:689] - [Get-MonkeySharePointOnlineExternalLink] - The SharePoint Online external links query did not return any data in 00000-xxxx-xxx tenant - warning - - SPSExternalLinksEmptyResponse
WARNING: [12:31:15:879] - [Get-MonkeySPSWebsForUser] - Unable to get site properties for  - warning - - SPSUnableToGetSites

Account has Global Administrator Role

**Comment by silverhack** [comment]
Hi @burak40 hope you're doing well, 

Are you getting a null reference exception? What is the value of the **$assets** variable? NULL? 

Please, note that these warnings are not indications of errors, but indications that some features are NOT configured in your Tenant (i.e. Roaming properties, B2B features, etc..). On the other hand, it seems that SharePoint online is not correctly configured for your user. You MUST grant your user access to a SharePoint site. As a best security practice, you should always add users to a SharePoint group, instead using Global Administrator role. 

Please, start with Monkey365 docs, as well as with information regarding how to configure SharePoint online. Below you can find more information:

[https://learn.microsoft.com/en-us/sharepoint/understanding-permission-levels](https://learn.microsoft.com/en-us/sharepoint/understanding-permission-levels)
[https://learn.microsoft.com/en-us/sharepoint/customize-sharepoint-site-permissions](https://learn.microsoft.com/en-us/sharepoint/customize-sharepoint-site-permissions)
[https://www.enjoysharepoint.com/add-user-to-sharepoint-site/](https://www.enjoysharepoint.com/add-user-to-sharepoint-site/)

Thanks,

**Comment by alvesrafaelc** [comment]
first of all, congratulations for this project.

I'm running the query and getting the results:

$assets = Invoke-Monkey365 -ExportTo HTML -PromptBehavior SelectAccount -IncludeAzureActiveDirectory

AVISO: [18:11:34:772] - [Get-MonkeyADApplication] - The Applications Role Assignments query did not return any data in XXXX-XXXX-XXXX tenant - warning - DESKTOPPC.local - AzureGraphAppRBACEmptyResponse
AVISO: [18:12:00:598] - [Get-MonkeyADPasswordPolicy] - The Azure AD password template policy query did not return any data in XXXX-XXXX-XXXX tenant - warning - DESKTOPPC.local - AzurePortalTemplatePolicyEmptyResponse
AVISO: [18:12:08:711] - [Get-MonkeyADPortalDeviceSetting] - The Azure AD device settings query did not return any data in XXXX-XXXX-XXXX tenant - warning - DESKTOPPC.local - AzurePortalDevicesEmptyResponse
AVISO: [18:12:16:456] - [Get-MonkeyADDirectoryProperty] - The Azure AD B2B directory properties query did not return any data in XXXX-XXXX-XXXX tenant - warning - DESKTOPPC.local - AzurePortalEmptyResponse
AVISO: [18:12:24:667] - [Get-MonkeyADRoamingInfo] - The Azure AD Roaming properties query did not return any data in XXXX-XXXX-XXXX tenant - warning - DESKTOPPC.local - AzurePortalRoamingEmptyResponse
AVISO: [18:13:29:289] - [Get-MonkeyADManagedApplication] - The Azure AD managed app user permissions query did not return any data in XXXX-XXXX-XXXX tenant - warning - DESKTOPPC.local - AzurePortalManagedAppEmptyResponse
