### ISSUE TITLE
[Bug]:  Analysis : "Kubernetes"

### ISSUE THREAD

**Issue by Ryaad** [silverhack/monkey365#42]
**What happened?**  
Hi ! I want to produce a report with an analysis of Kubernetes but when I try with the "Kubernetes" parameter it doesn't work. There is a problem in the exportation, no matter to what I export it. I noticed in the code of the function "Invoke-Monkey365" that Kubernetes is missing, I don't know if the problem is from here or from my configuration (I am novice). If I change the "Kubernetes" with any other analysis's parameter, it works very well and if I use "All", I don't have the Kubernetes in my report.

<img width="576" alt="Kube-Monkey" src="https://user-images.githubusercontent.com/95927185/209169492-fcc65cb3-794c-451f-84e6-5fe08a2024b6.PNG">

<img width="346" alt="Invoke-Monkey365" src="https://user-images.githubusercontent.com/95927185/209166780-94b82cc4-6a0f-41f3-ad00-52ded511db30.PNG">

**Comment by silverhack** [comment]
Hi @Ryaad hope you're doing well and thanks for submitting this, it's really appreciated. 

Although Monkey365 has a kubernetes plugin, only [CIS for Azure and Microsoft 365](https://silverhack.github.io/monkey365/security_checks/overview/) benchmarks are supported by the tool. More standards will be added in next releases, including [Kubernetes CIS benchmark](https://learn.microsoft.com/en-us/azure/aks/cis-kubernetes). For that reason the scan returns an **empty object**. 

On the other hand, Monkey365 should shutdown gracefully when an empty object is returned, and a check would be needed needed to avoid issues when creating a new html report. I'll create a new issue for that. 

Cheers,
