### ISSUE TITLE
Execute more than one control

### ISSUE THREAD

**Issue by gaudium91** [silverhack/monkey365#47]
Hi, is possbile to execute more than one "Analysis" with one comand execution ?

Many Thanks,

Guido

**Comment by silverhack** [comment]
Hi @gaudium91 hope you're doing well, 

It's not a bug. The answer is yes, you can populate the **--Analysis** flag with [multiple values](https://silverhack.github.io/monkey365/configuration/microsoft365-options/). To avoid misspelling commands, please make use of TAB-completion in PowerShell.

Please, check the docs, as all documentation is published at [https://silverhack.github.io/monkey365](https://silverhack.github.io/monkey365). 

For the next time, and If you're experiencing a problem that you feel **is not a bug**, please, consider to use the [GitHub discussions](https://github.com/silverhack/monkey365/discussions).

Cheers,

**Comment by gaudium91** [comment]
Ok thanks, sorry for the mistake

Many Thanks,
Guido
