### ISSUE TITLE
Exchange Online Remote PowerShell Migration

### ISSUE THREAD

**Issue by silverhack** [silverhack/monkey365#48]
**Is your feature request related to a problem? Please describe.**
Remote PowerShell (RPS) protocol is deprecated and will be decommissioned in the near future (July 1, 2023). Monkey365 is still connecting to Exchange Online through Remote PowerShell (RPS) and therefore should be migrated to REST API.

**Describe the solution you'd like**
Migrate all Exchange Online related plugins and update Monkey365 codebase to use the new EXO REST endpoints

**Additional context**
[Remote PowerShell Deprecation](https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-remote-powershell-in-exchange-online-re-enabling/ba-p/3779692)

**Comment by silverhack** [comment]
Hi @Spanjoekel, 

Still working on it. The expectation is to publish the new version in early June, but I'll do my best and I will try to get this ready asap.

Please, note that new version contains a lot of improvements and major fixes and enhacements, and I am the only one that is working on it xP. 

Thanks! :D

**Comment by Spanjoekel** [comment]
I understand and thanks you for all your effort!
