### ISSUE TITLE
[Bug]: Wrong description for PostGreSQL log_retention

### ISSUE THREAD

**Issue by qbrusa** [silverhack/monkey365#49]
**What happened?**  
PostgreSQL configuration check for log_retention have the same description of log_disconnection

**How to reproduce it**  
Just compare the two links below 

- https://github.com/silverhack/monkey365/blob/7cd95c1f5ccfe828075ddfd1e90031ce0a72e2ca/rules/findings/Azure/Databases/PostgreSQL/CIS1.4/azure-postgresql-log-retention-days.json
- https://github.com/silverhack/monkey365/blob/main/rules/findings/Azure/Databases/PostgreSQL/CIS1.4/azure-postgresql-log-disconnections-disabled.json

**Expected behavior**  
PostGre SQL should have another description

**Screenshots or Logs**  
n/a

**From where are you running Monkey365?**  
Please, complete the following information:
 - Resource: workstation
 - OS: windows
 - PowerShell Version [`$PsVersionTable`]: PowerShell 7.3.4
 - Monkey365 Version: latest
 - Others:

**Additional context**
n/a

**Comment by silverhack** [comment]
Hi @qbrusa, 

Thanks! I've updated the rules and this is now fixed in dev branch. 

Cheers,
