### ISSUE TITLE
[Bug]: DEBUG messages are displayed

### ISSUE THREAD

**Issue by qbrusa** [silverhack/monkey365#50]
**What happened?**  
DEBUG messages are displayed when running Azure ALL scan

**How to reproduce it**  
Run a a scan with Instance=Azure, Analysis=All

**Expected behavior**  
I think this message are not necessary for standard users, or maybe a -Debug option should be added

**Screenshots or Logs**  
<img width="557" alt="image" src="https://github.com/silverhack/monkey365/assets/122641985/b5b8f26f-209e-47a7-89f0-b977e8beee88">

**From where are you running Monkey365?**  
Please, complete the following information:
 - Resource: workstation)
 - OS: Windows
 - PowerShell Version [`$PsVersionTable`]: 7.3.4
 - Monkey365 Version: 0.85 beta
 - Others:

**Additional context**

**Comment by silverhack** [comment]
Hi @qbrusa, 

Thanks for submitting this! I can reproduce the issue and this should be fixed now in dev branch. 

Cheers,
