### ISSUE TITLE
Security and Compliance PowerShell RPS Migration

### ISSUE THREAD

**Issue by silverhack** [silverhack/monkey365#59]
**Is your feature request related to a problem? Please describe.**
Remote PowerShell (RPS) protocol is deprecated and will be decommissioned in the near future (October 2023). Monkey365 is still connecting to Security and Compliance through Remote PowerShell (RPS) and therefore should be migrated to REST API.

**Describe the solution you'd like**
Migrate all Security and Compliance related plugins and update Monkey365 codebase to use the new REST endpoints

**Additional context**
[Deprecation of Remote PowerShell (RPS) Protocol in Security and Compliance PowerShell](https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-remote-powershell-rps-protocol-in-security-and/ba-p/3815432)

**Comment by silverhack** [comment]
It's now migrated on dev branch. It will be merged to main branch asap

**Comment by silverhack** [comment]
This enhacement was reopened. 

As far as I can see CmdLets that requiring an active PowerShell PSSession were migrated to a REST-based commands. Monkey365 should migrate those CmdLets and to route commands to REST.

**Comment by master-qwerty** [comment]
Hi, 

I am unsure if this is related to this, but I can see below the warning and not results for Security and Compliance. 
Or do I have to change some parameters? 

`WARNING: Your connection has been redirected to the following URI: "https://eur06b.ps.compliance.protection.outlook.com/Powershell-LiveId?BasicAuthToOAuthConversion=true;PSVersion=5.1.22621.2506"
WARNING: Unable to connect to Exchange Compliance Center`

Parameters:
`$param = @{
    Instance       = 'Microsoft365';
    Analysis       = @("Microsoft365", "ExchangeOnline", "MicrosoftTeams", "PurView");;
    DeviceCode     = $true;
    IncludeAzureAD = $true;
    ExportTo       = @("CSV", "JSON", "HTML");
}`

Tested with this release:
`[Monkey365 v0.91.1-beta](https://github.com/silverhack/monkey365/releases/tag/v0.91.1-beta)`

thanks in advance,

**Comment by silverhack** [comment]
Hi @master-qwerty I believe is related to this issue and should be fixed in the next version.I'll leave this opened to better track it.

Thanks

**Comment by silverhack** [comment]
Migration is now completed and RPS was migrated to REST based queries.
