### ISSUE TITLE
[Bug]: Get-AstFunction is not recognized

### ISSUE THREAD

**Issue by qbrusa** [silverhack/monkey365#64]
**What happened?**  
When I import monkey365 with command "Import-Module .\monkey365.psm1" I have an error message about Get-AstFunction

**How to reproduce it**  
1. What command are you running?
` Import-Module .\monkey365.psm1`
2. See error

**Expected behavior**  

**Screenshots or Logs**  
![import_error](https://github.com/silverhack/monkey365/assets/122641985/efe3bd58-60b5-44b8-b62e-964c6b8182a7)

**From where are you running Monkey365?**  
Please, complete the following information:
 - Resource: VirtualBox VM 
 - OS: Windows 10
 - PowerShell Version [`$PsVersionTable`]: 5.1.19041.2673
 - Monkey365 Version: latest
 - Others:

**Additional context**

**Comment by silverhack** [comment]
Hi @qbrusa, 

It is not a bug and you're using the "Import-Module" incorrectly. Please, see docs about how to correctly import a module in PowerShell. 

[https://silverhack.github.io/monkey365/install-instructions/](https://silverhack.github.io/monkey365/install-instructions/)
[https://learn.microsoft.com/en-us/powershell/scripting/developer/module/importing-a-powershell-module?view=powershell-7.3](https://learn.microsoft.com/en-us/powershell/scripting/developer/module/importing-a-powershell-module?view=powershell-7.3)

**Comment by qbrusa** [comment]
Hi @silverhack, Finaly I have found that  Import-Module .\monkey365.ps**d**1 works. But If I want to use the default command to import a module, Powershell return to me that no valide module exist :
![image](https://github.com/silverhack/monkey365/assets/122641985/92c2cafe-f2f1-4f95-b6f3-c72d66f65c79)

I think you could update your doc (or push your Powershell module in PSGallery ?), and thank you for your great work.

**Comment by silverhack** [comment]
Hi @qbrusa there is no error and your issue is the same as the last one. You're seeing these errors because the folder does not have the same name as the PSD1. You should rename the folder from Monkey365-main to Monkey365. Once the name is changed you will be able to import the module. And all is explained [here](https://learn.microsoft.com/fr-fr/powershell/scripting/developer/module/how-to-import-cmdlets-using-modules?view=powershell-7.4).

Cheers,
