### ISSUE TITLE
[Bug]: Monkey365 not works and multiple error message appears

### ISSUE THREAD

**Issue by qbrusa** [silverhack/monkey365#65]
**What happened?**  
When I run monkey365 scan for m365 with params, I have a lot of error message (see screenshot)

**How to reproduce it**  
1. What command are you running?
Invoke-Monkey365 @param
3. See error

**Expected behavior**  
No error and Monkey works :)

**Screenshots or Logs**  
![2023-08-25 15_49_30-Windows 10  Toolkit  Running  - Oracle VM VirtualBox](https://github.com/silverhack/monkey365/assets/122641985/3cbee9d9-a8e5-4d0b-afbe-23a5edbd565f)

**From where are you running Monkey365?**  
Please, complete the following information:
 - Resource: Virutalbox VM
 - OS: Windows 10
 - PowerShell Version [`$PsVersionTable`]: 5.x or 7.x is the same
 - Monkey365 Version: latest
 - Others:

**Additional context**

**Comment by silverhack** [comment]
Hi @qbrusa,

It is not a bug and you're import it incorrectly. Please, see docs about how to import a PowerShell module. 

https://silverhack.github.io/monkey365/install-instructions/
https://learn.microsoft.com/en-us/powershell/scripting/developer/module/importing-a-powershell-module?view=powershell-7.3
