### ISSUE TITLE
Missing roles

### ISSUE THREAD

**Issue by nurfed1** [silverhack/monkey365#68]
https://github.com/silverhack/monkey365/blob/main/rules/conditions/aad-privileged-roles.json is missing multiple privileged  [roles](https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference), such as user administrator

**Comment by silverhack** [comment]
Hey @nurfed1, 

Thank you for catching this. That condition file is outdated and should be updated to reflect all new Azure AD roles. 

I'm currently working in new features, and rulesets, conditions and dynamic queries are all in the TODO list.

In the meantime, I will update as soon as I can the dev codebase with new condition files. 

Cheers,

**Comment by silverhack** [comment]
Both main and dev branches contains latest roles from Microsoft Entra ID. 

Cheers,
