### ISSUE TITLE
[Bug]:  Attribute supportedServices of JSON output file aad_domains.json is of ambiguous type. 

### ISSUE THREAD

**Issue by SCSInet22** [silverhack/monkey365#69]
**What happened?**  

When running Monkey365 with the -JSON output option, one of the JSON files produced, `aad_domains.json`, produces an ambiguous attribute type under attribute "supportedServices".  

In the event of no supported services, it presents an array type:

`"supportedServices": [],`

In the event of supported services being present, it presents as a single comma delimited string:

`"supportedServices":  "Email,OfficeCommunicationsOnline",`

**How to reproduce it**  

1. `Invoke-Monkey365 -ExportTo JSON ........ .......`
2. Open result file aad_domains.json in a text editor. 

**Expected behavior**  
Expectation 1: An type should be returned in either case:

`"supportedServices": [],`
-OR-
`"supportedServices": ["Email","OfficeCommunicationsOnline","Intune"],`

Expectation 2:  A string type should be returned in either case:

`"supportedServices": "",`
-OR-
`"supportedServices": "Email,OfficeCommunicationsOnline,Intune",`

**From where are you running Monkey365?**  
Please, complete the following information:
 - Resource: Workstation
 - OS: Win10
 - PowerShell Version : 5.1.19041.3031
 - Monkey365 Version: 0.85

**Comment by silverhack** [comment]
Hi @SCSInet22 thanks for submitting this. 

The **supportedServices** property was used by some outdated rules that were looking for literal strings, rather than arrays. 

Working on a patch for this and other issues and will be uploaded into the dev branch. 

Cheers,

**Comment by silverhack** [comment]
Fixed in main branch, but please, note that JSON and CSV output will be replaced in next releases of Monkey365. More info [here](https://github.com/silverhack/monkey365/issues/76).

Cheers,
