### ISSUE TITLE
Multiple forms of output in one zip file

### ISSUE THREAD

**Issue by dom34** [silverhack/monkey365#78]
**Is your feature request related to a problem? Please describe.**
I often find myself needing to transfer the output of Monkey365 from machine to machine. To do that I have to find the various bits of output, the log file and zip them up myself. That all takes time.

**Describe the solution you'd like**
An additional value for ``ExportTo``, for example ``ZIP``, that generates HTML, JSON and CSV output, then zips it up together with any log files pertaining to the run, and either puts it in ``OutDir`` or in a system temporary directory, for example ``/tmp/`` on a Linux system. Monkey365 should report the full path to the output zip file at the end of the run.

**Describe alternatives you've considered**
Zipping it up myself (see above), which is what I do at the moment.

**Comment by silverhack** [comment]
Hi @dom34, 

This is a great idea! I'll explore the posibility of compressing files into different formats. I'll get back to you soon. 

Cheers,

**Comment by silverhack** [comment]
Feature included!

Cheers,
