### ISSUE TITLE
[Bug]: Admin Consent to Enterprise Applications - azure-activedirectory-users-can-consent-apps-data-access.json

### ISSUE THREAD

**Issue by cmking94** [silverhack/monkey365#86]
**What happened?**  
The current finding for Admin Consent to Enterprise Applications in the finding "azure-activedirectory-users-can-consent-apps-data-access.json" is no longer applicable. The finding is now under Entra ID > Applications > Enterprise Applications > Consent and permissions. Also, the finding can be located with "Get-MsolCompanyInformation | Select-Object UsersPermissionToUserConsentToAppEnabled". 

**Expected behavior**  
The resource in the HTML report for the "Ensure That 'Users Can Consent To Apps Accessing Company Data On Their Behalf' Is Set To 'No'" configuration shows passed, but my O365 tenant has "Allow user consent for apps" selected. The JSON file "aad_managed_app_user_settings" shows 'null' for the "usersCanAllowAppsToAccessData" finding. 

**Screenshots or Logs**  
![image](https://github.com/silverhack/monkey365/assets/80839896/d08a6527-693b-4e82-b456-6a1c3a6fa6da)

**From where are you running Monkey365?**  
 - Resource: Workstation
 - OS: Windows
 - PowerShell Version [`$PsVersionTable`]: 5.1.20348.2110
 - Monkey365 Version: v0.91.2-beta

**Comment by silverhack** [comment]
Hi @cmking94 thanks for catching this! it's really appreciated. 

Just to mention that this rule is for CIS 1.4 and is that rule was superseded by a [more specific one](https://github.com/silverhack/monkey365/blob/main/rules/findings/AzureAD/Users/CIS1.5/azure-activedirectory-users-can-consent-apps-data-access-trusted-publishers-disabled.json) that is checking for trusted publisher apps.

I'll update the rule as soon as I can. 

Thanks!

**Comment by cmking94** [comment]
This was the field I was looking for and I understand the finding results, thanks for the quick response!

**Comment by silverhack** [comment]
Hi @cmking94, 

This is now fixed on dev branch. 

Cheers,
