### ISSUE TITLE
Updating the solution text

### ISSUE THREAD

**Issue by Frenzaahh** [silverhack/monkey365#88]
Currently an intern student researching Azure Entra ID security auditing.

I've came across this project and I've seen that some remediation's are outdated and need some updates and I would like to help to update these, because I can use the product for free.

**Comment by silverhack** [comment]
That's amazing! Thanks 😎

Remediation text was extracted from official CIS benchmarks for both Azure and M365, and as far as I can see both documents were upgraded to 2.0 versions, so it would be great to update/create findings to align these with recent CIS update. 

[https://www.cisecurity.org/benchmark/azure](https://www.cisecurity.org/benchmark/azure)

[https://www.cisecurity.org/benchmark/microsoft_365](https://www.cisecurity.org/benchmark/microsoft_365)

Cheers
