### ISSUE TITLE
Update to latest CIS Benchmark

### ISSUE THREAD

**Issue by cheahengsoon** [silverhack/monkey365#96]
**Is your feature request related to a problem? Please describe.**
The CIS Benchmark not up to date

**Describe the solution you'd like**
Update to latest CIS Benchmark

**Comment by silverhack** [comment]
This is now updated to V2 in [main release](https://github.com/silverhack/monkey365/releases/tag/v0.91.3-beta). 

Cheers,

**Comment by softengsistemas** [comment]
Thanks for updating to the CIS Benchmark 2.0, but the last version is 3.1.0. I've attached the PDF.
[CIS_Microsoft_365_Foundations_Benchmark_v3.1.0.pdf](https://github.com/user-attachments/files/15835955/CIS_Microsoft_365_Foundations_Benchmark_v3.1.0.pdf)

**Comment by silverhack** [comment]
Hi @softengsistemas I know but thanks! 

Just to mention that contributors are encouraged to propose their contributions as pull requests to the dev branch. This branch will periodically be merged to the main branch. 

Thanks for using Monkey365. 
Cheers,

**Comment by ZuuXs** [comment]
@silverhack 
Can we change the whole baseline ? like switching to SCuBA. Also if you can explain how we can convert the framework to a JSON and how the code interract with the rules of the JSON file

**Comment by silverhack** [comment]
Hi @ZuuXs,  

Depending on how many frameworks you have configured, you will be able to switch between them with the -Ruleset flag. You can find more information about how to create custom rules [here](https://silverhack.github.io/monkey365/security_checks/overview/) and [here](https://silverhack.github.io/monkey365/security_checks/custom-rule/) and [here](https://silverhack.github.io/monkey365/security_checks/custom-ruleset/)
